# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5274226df7eec7016b95303cae61e766205ad1a6d35f99906c41e30d64c18f23bd6e48712102446a2471f341bc32ec5c31c601707ce587954681cecd5b7f543

test:
  secret_key_base: dd8b517142913e564a5f362d4ff12dbd48e5687d1927ffc81ec03510f3b469990dea56f1fbd912df600197c0728da12be06da429cf3edfe645a2e47559d2779d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
